### ISSUE TITLE
Use Draco Mesh Compression

### ISSUE THREAD

**Issue by zicklag** [katharostech/arsenal#13]
Use [Draco](https://github.com/google/draco) mesh compression for mesh export and loading.

- [ ] Wrap Draco C++ library in Rust
- [ ] Use Draco when exporting meshes from the Arsenal
- [ ] Make sure Draco compression is supported for loading meshes in game

**Comment by bwasty** [comment]
We've discussed adding Draco loading support to the `gltf` crate a long while ago (I'm a contributor there -> https://github.com/gltf-rs). But it's a major project and so far there isn't even an issue - I would suggest opening one there to discuss it.

For generating the draco compressed file, it might be an option to use an external tool like https://github.com/TimvanScherpenzeel/gltf-to-glb (easier than directly writing draco I guess).

**Comment by zicklag** [comment]
Thanks. I created an issue: https://github.com/gltf-rs/gltf/issues/242.

**Comment by zicklag** [comment]
Closing in favor of #93.
