### ISSUE TITLE
Clean Up and Organize Makefile

### ISSUE THREAD

**Issue by zicklag** [katharostech/arsenal#26]
**In order to** streamline development and help automate tasks

**As a** Arsenal developer

**I want** to have common development and release tasks added to the Makefile

---

The current Makefile is a bit messy. We should go through and add the tasks that we actually want in there and organize it a bit.

**Comment by Raj2032** [comment]
Where is the link tot he makefile?

**Comment by zicklag** [comment]
Ah, the current Makefile is [here](https://github.com/katharostech/arsenal/blob/master/Makefile.toml) and the documentation for the format is [here](https://github.com/sagiegurari/cargo-make).

I'm not exactly sure what tasks we want to add to the makefile, but a good start would be something that essentially just runs through the steps in [Building Arsenal](https://katharostech.github.io/arsenal/development-guide/building.html). After that we're probably going to want something to run Rust Format and Clippy on all of the Rust code.

**Comment by zicklag** [comment]
We might be getting rid of the makefile anyway. Closing for now.
