### ISSUE TITLE
Approximation alpha release date

### ISSUE THREAD

**Issue by Raj2032** [katharostech/arsenal#3]
Hi, I am pretty interested in this project and I may end up contributing to this project in the near project.

I would like to know if there is an approximate alpha release date?

**Comment by zicklag** [comment]
Hi @Raj2032! Glad to hear of your interest in the project.

Right now we don't have any way to provide an accurate timeline for arsenal development ( see our [FAQ](https://katharostech.github.io/arsenal/FAQ.html#when-do-you-intend-to-release-the-first-version-10) ).
