### ISSUE TITLE
Basic glTF Export

### ISSUE THREAD

**Issue by zicklag** [katharostech/arsenal#5]
We need to get basic scenes with the mesh geometry exporting to glTF. The export functionality will be implemented in Rust and multi-threaded as much as possible.

- [x] Export scenes and node trees
- [x] Export meshes
  - Ignore materials and textures: just export geometry
  - [x] Export mesh buffer data
- [x] Benchmark Rust vs. Python
  - We want to prove out that there is performance gained by implementing the Blender plugin in Rust
  - [x] Write an equivalent Python implementation of the exporter -- Just tested the Khronos Group's official Blender plugin
  - [x] Benchmark performance compared to the Rust version -- Rust version was 22 times faster in the [initial benchmark](https://community.amethyst.rs/t/arsenal-the-vision-for-a-full-amethyst-blender-integration/911/9?u=zicklag).
  - :x:  Add parallelization to the Rust implementation wherever possible -- Might skip this for now as the flamgraph shows that the parallelize-able section of the program takes almost no time.
    * Skipped because the new structure requires python access the whole time which prevents releasing the GIL
  - :x: Compare performance of the parallelized Rust implementation and the Python implementation
- :x: Export cameras
  - Skipped because we don't need it now. We'll put it in a later iteration
- :x: Export lights -- May want to skip this for now because it isn't supported by the `gltf-json` library we are using for glTF exporting
  - Skipped because we don't need it now. We'll put it in a later iteration

**Comment by Raj2032** [comment]
Why can't we just use the blend file?

**Comment by zicklag** [comment]
There are three reasons:

1. **Maintenance:** Keeping up with the Blender file format could be time-consuming as it is a moving target. Comparatively, the glTF format is very simple and standardized.
2. **Storage:** The blender format contains a lot of metadata that we don't need for a game, such as the Blender UI layout.
3. **Efficiency:** If you use the Blender file format, the game would have to decode the .blend file while the game is running. This would involve going through more information than is actually needed in the game and would require more CPU to get the required data. glTF is a very dense format that compactly stores the information we need while also facilitating efficient extraction into a running game.

**Comment by Raj2032** [comment]
@zicklag I see and I understand.

What if I am designing a level map and I am just creating random objects to fit in the level. How would that work exactly? Like say I saved a level map as a gltf format, then what if I wanted to add something. Can I (using the Blender tools) add a cube (as an example) and if I press safe, would that cube automatically be converted into a gltf format?

**Comment by zicklag** [comment]
You, as a game developer, will not have to deal with the glTF export at all. The glTF export happens automatically before Blender runs your game and the developer doesn't even have to know what happens. All changes to the game scenes will be done through Blender, just like it was with Armory. In other words, glTF for Arsenal is what the .arm format was for Armory.

> Can I (using the Blender tools) add a cube (as an example) and if I press save, would that cube automatically be converted into a gltf format?

The conversion will automatically happen when you click "Arsenal Run". So the workflow is:

1. Edit my scene in Blender
2. Click "Run"
3. The Blender scene is automatically exported to glTF in the background
4. The game runs and loads the glTF game scene.
