### ISSUE TITLE
Expressing my interest in developing Arsenal

### ISSUE THREAD

**Issue by Raj2032** [katharostech/arsenal#54]
Hi, so currently I have basic experience with Rust. I was wondering if there is some easy task I could do to help develop Arsenal using Rust?

**Comment by zicklag** [comment]
Hi @Raj2032. Really glad you want to help! Right now there is not much easy stuff yet. There is a bug ( #55 ) that you could work on, but that might be a little advanced. If you want to try it and have any questions I would be glad to answer them.

Right now I am trying to get scripting setup ( #10 ) and that is blocking most other work, but once that is done, hopefully there will be more to work on.

Other than that, it would be good just to have more people test out our first [release](https://github.com/katharostech/arsenal/releases/tag/v0.1.0) to make sure that it works on on different computers and operating systems.

---

I re-titled this issue so we can keep it open as a place for people to ask how they can help.

**Comment by Raj2032** [comment]
@zicklag Hi,

> There is a bug ( #55 ) that you could work on, but that might be a little advanced. If you want to try it and have any questions I would be glad to answer them. If you want to work on it, I can throw a developer guide up real quick to help you get started.

Could you please give me the developer guide as that would really help me out :)

**Comment by zicklag** [comment]
Sure, I've got to write it, but it shouldn't take long. I won't be able to get to it tonight, but I'll try to do it tomorrow.

**Comment by Raj2032** [comment]
@zicklag Thanks and sorry for the trouble. I will try and do my best to work on this, but I apologise if I can't solve this problem.

**Comment by zicklag** [comment]
No problem at all. We welcome any help. As long as you're willing to try at it, I'm good helping you figure it out. Wether you can fix it or not you'll probably learn something and that will help you solve other problems later. :+1:

**Comment by erlend-sh** [comment]
While waiting for the developer guide, how far into the [Amethyst docs ](https://amethyst.rs/doc) are you @Raj2032 ? The more you learn about Amethyst, the more you’ll be able to help out with Arsenal as well. Also zicklag is unable to join our Discord chat where many helpful people hang out, so you could be Arsenal’s liaison there ;)

**Comment by zicklag** [comment]
I'm actually going to close this issue and open #57 for questions about helping development so that I can edit the post without erasing @Raj2032's original post. We can move discussion there.
