### ISSUE TITLE
How Can I Help Arsenal Development?

### ISSUE THREAD

**Issue by zicklag** [katharostech/arsenal#57]
Hello everybody, this is a thread where you can ask questions related to helping Arsenal development. If you want to help out, but don't quite know how or you have questions how you can help, don't hesitate to comment!

Also, be sure to check out the [contributing guide](https://katharostech.github.io/arsenal/contributing.html) in the documentation.

**Comment by Raj2032** [comment]
Hey man, so what is the link to the Discord channel I can access and view for Arsenal?

**Comment by zicklag** [comment]
Arsenal doesn't actually have a Discord. @erlend-sh was referring to the [Amethyst Discord server](https://discord.gg/amethyst).

**Comment by zicklag** [comment]
Oh, also, I won't be able to get the dev guide out today as I decided to do some re-organization to the project to make it make more sense and to make it easier to explain in a guide. Still shouldn't take longer than a day or two. I'll let you know when I finish it.

**Comment by zicklag** [comment]
@Raj2032 It isn't writing Rust, but if you wanted to, you could help write the makefile ( #26 ). In the dev guide I'm going to document how everything is put together and how to build it manually. Once you have that you could write the Makefile jobs to automate the tasks and then document the make jobs. That could be a good first contribution.

**Comment by Raj2032** [comment]
Hi, does this _makefile_ build the entire engine?

**Comment by zicklag** [comment]
It should, but right now it doesn't. I haven't updated with the latest steps necessary to build the engine.

**Comment by Raj2032** [comment]
Does it only build the addon? Or Blender and everything else?

**Comment by zicklag** [comment]
It only builds the addon and everything that goes into it, but not Blender. The Arsenal plugin should work on any normal Blender 2.8 build so we don't have any reason to build it ourselves.

There are a few different pieces to the addon that are somewhat separate from each-other. I'm going to document how that works in the Dev guide which I can hopefully get a first minimal release out for tonight.

**Comment by Raj2032** [comment]
Oh ok cool thanks I will take a look into this.

**Comment by zicklag** [comment]
@Raj2032 I've still got to add more instructions on building and such, but I revised the [Architecture](https://katharostech.github.io/arsenal/development-guide/architecture.html) page and put it in a new "Development Guide" section. More information is comming! :hammer: :information_source:  :rocket:

**Comment by zicklag** [comment]
I just pushed a whole set of new documents including how to build Arsenal. Tell me if you have any trouble or notice any errors.

**Comment by Raj2032** [comment]
@zicklag Thanks I will take a look into it.

**Comment by zicklag** [comment]
Issue has been moved to Taiga: https://tree.taiga.io/project/zicklag-arsenal/issue/57

The GitHub issue manager will now be disabled. All comments should be directed to Taiga.

**Comment by zicklag** [comment]
Closing as we prune issues.
