### ISSUE TITLE
How to get the addon

### ISSUE THREAD

**Issue by Raj2032** [katharostech/arsenal#69]
I can't get the Aresenal addon for Blender 2.8 **stable** release. I want to get this addon to test it out. I apologise I have not been here and helping with the community.

Also I just want to know, when runing the game using ARsenal addon, would it be based on the Eevee Renderer?

**Comment by zicklag** [comment]
> I can't get the Aresenal addon for Blender 2.8 stable release. I want to get this addon to test it out.

Sure thing, I've just got to download it and test it out. I'll make any changes necessary and make a new release for it.

> I apologise I have not been here and helping with the community.

Absolutely no problem. Put in what time you can if you *want* to help and if you don't have the time there's no pressure.

> Also I just want to know, when runing the game using ARsenal addon, would it be based on the Eevee Renderer?

Nope. Once an Arsenal game is running, it will have absolutely nothing from Blender's code inside of the game. This  is a deliberate design decision and is actually very important from a licensing perspective, because having GPL licensed Blender code in your game would make it nearly impossible to sell your game commercially.

Currently Arsenal is using the old Amethyst 0.10 renderer, but once the new Amethyst renderer that is based on [Rendy] gets OpenGL support, Arsenal will switch to using that one.

[Rendy]: https://github.com/amethyst/rendy

**Comment by zicklag** [comment]
@Raj2032 It looks like the currently released version of the plugin works fine with Blender 2.8 stable. You should be able to install it with the instructions in the [Getting Started guide][guide].

[guide]: https://katharostech.github.io/arsenal/getting-started.html

**Comment by Raj2032** [comment]
@zicklag So with the new Rendy renderer, would it support emissions property? What about glosssy property would it also support that? Would you be able to make the products shiny?

**Comment by Raj2032** [comment]
> @Raj2032 It looks like the currently released version of the plugin works fine with Blender 2.8 stable. You should be able to install it with the instructions in the [Getting Started guide](https://katharostech.github.io/arsenal/getting-started.html).

![image](https://user-images.githubusercontent.com/29293830/62342219-70119d80-b529-11e9-81ff-b8ede6537f9d.png)
It looks like it is missing or something?

**Comment by zicklag** [comment]
Yes, it will be able to support any of that stuff. Rendy is a low-level "build-a-renderer kit", as they describe it. With it you could build any kind of renderer at all, whether it be a toon renderer or a very realistic one. That said, it isn't a renderer in-and-of-itself, just a tool to build one. That is why we will be using the Amethyst renderer that will be built on top of Rendy.

For an example of what you can accomplish with Rendy, see the [Rendy PBR](https://github.com/termhn/rendy-pbr) project. Most of the features developed there will most likely be integrated into the Amethyst renderer in some form.

**Comment by Raj2032** [comment]
@zicklag 

> That is why we will be using the Amethyst renderer that will be built on top of Rendy.

So that means that the Amethyst renderer that will be built on top of Rendy, would that support glossy properties (from Blender) and emission properties as well?

**Comment by Raj2032** [comment]
> Yes, it will be able to support any of that stuff. Rendy is a low-level "build-a-renderer kit", as they describe it. With it you could build any kind of renderer at all, whether it be a toon renderer or a very realistic one. That said, it isn't a renderer in-and-of-itself, just a tool to build one. That is why we will be using the Amethyst renderer that will be built on top of Rendy.
> 
> For an example of what you can accomplish with Rendy, see the [Rendy PBR](https://github.com/termhn/rendy-pbr) project. Most of the features developed there will most likely be integrated into the Amethyst renderer in some form.

I see thanks for that.

**Comment by zicklag** [comment]
I'm going to close this now. Don't hesitate to open a new issue if you have more questions.

**Comment by Raj2032** [comment]
@zicklag Hey man sorry I have one last question (for now), how many people are working on this project, and how fast is it going the project development? Do you know by any chance when alpha is going to be released?

I have been trying to apply for internships for Rust development so I hope I can get in so I can learn as much as possible so I can help the team once I become more advanced.

My university has started again so I don't have as much time to study Rust but yeah I hope I do get an internship position.

**Comment by zicklag** [comment]
Right now I'm the only one working on Arsenal itself, but there are a lot more people working on Amehtyst, which is where the work actually needs to be done right now, to get scripting support. As far as project development speed and when we might have an alpha, there is no good way to determine that at this point. So far we have been working steadily on it and making progress in our investigations and documentation, though. We will be posting updates on all of our progress [on our website][web] so you'll be able to tell what's been going on.

[web]: https://katharostech.com/tag/arsenal

We're glad you want to help and that you're looking into getting deeper into Rust. Hopefully once we get the necessary foundation for scripting finished, there will be more easier things to contribute to inside of Arsenal. In the meantime, you could also look for [easy issues][easy] or other issues in Amethyst that you might be able to help with. Any help to Amethyst will also be a benefit to Arsenal.

[easy]: https://github.com/amethyst/amethyst/issues?q=is%3Aopen+is%3Aissue+label%3A%22diff%3A+easy%22

Again, thanks for your interest!

**Comment by Raj2032** [comment]
@zicklag 

> Right now I'm the only one working on Arsenal itself, but there are a lot more people working on Amehtyst, which is where the work actually needs to be done right now, to get scripting support. As far as project development speed and when we might have an alpha, there is no good way to determine that at this point. So far we have been working steadily on it and making progress in our investigations and documentation, though. We will be posting updates on all of our progress [on our website](https://katharostech.com/tag/arsenal) so you'll be able to tell what's been going on.
> 
> We're glad you want to help and that you're looking into getting deeper into Rust. Hopefully once we get the necessary foundation for scripting finished, there will be more easier things to contribute to inside of Arsenal. In the meantime, you could also look for [easy issues](https://github.com/amethyst/amethyst/issues?q=is%3Aopen+is%3Aissue+label%3A%22diff%3A+easy%22) or other issues in Amethyst that you might be able to help with. Any help to Amethyst will also be a benefit to Arsenal.
> 
> Again, thanks for your interest!

Thank you very much :)

So are you working on the Amethyst project as well by any chance, just asking out of curiosity?

**Comment by zicklag** [comment]
Yes, I'm am definitely going to be contributing to Amethyst and working on the features we need for Arsenal. Right now I'm working on evaluating a new ECS called [Legion] ( see [discussion] ) because it could make a big difference for scripting support, among other things, in Amethyst.

[Legion]: https://github.com/kabergstrom/legion
[discussion]: https://community.amethyst.rs/t/legion-ecs-discussion/965/14?u=zicklag
