### ISSUE TITLE
Iconic Arsenal logo needed

### ISSUE THREAD

**Issue by opax7** [katharostech/arsenal#72]
**In order to** easily identify Arsenal graphically

**As a** user or stakeholder who may or may not know about Arsenal

**I want** an epically iconic logo to remember Arsenal by

---

**Comment by zicklag** [comment]
We are open to contributions, concepts, or ideas for the logo from the community. The logo should be licensed under [CC-BY-3.0].

[CC-BY-3.0]: https://creativecommons.org/licenses/by/3.0/

---

My initial idea for the design was something like three missiles with some smoke behind them or somthing like that, but we are open to anything. We'd love to see anybody's concepts or hear ideas.

**Comment by zicklag** [comment]
Here's a concept, does anybody have any thoughts?

![logo svg](https://user-images.githubusercontent.com/25393315/63058562-a567a500-beb2-11e9-97d5-49ed50507678.png)

**Comment by erlend-sh** [comment]
There’s a bit too much going on there. Maybe drop the liftoff dust and just stack them up together?

https://images.app.goo.gl/88pBMW2gTNvSLj4D6

https://images.app.goo.gl/DbuE254o51m2HmxV9

https://images.app.goo.gl/HFxShJgF9ki5rb3d7

**Comment by zicklag** [comment]
Thanks for the feedback! I'll mess around with it and submit another concept.

**Comment by TMcSquared** [comment]
I think I'll have a go at it tonight as well.

**Comment by zicklag** [comment]
Cool! I could use any help I can get. :smiley:

**Comment by TMcSquared** [comment]
Any specific colors needed?

**Comment by zicklag** [comment]
I was thinking about orange and grey, but we're definitely open to other suggestions if you think there is anything that looks good.

**Comment by zicklag** [comment]
Issue has been moved to Taiga: https://tree.taiga.io/project/zicklag-arsenal/issue/72

The GitHub issue manager will now be disabled. All comments should be directed to Taiga.

**Comment by zicklag** [comment]
Logo was added with 47cc05696df7eaf78ad5bcffb053f5b8e1715243.
